### ISSUE TITLE
[edp-build]md5renamer在处理url时忽略了hash部分引起的bug

### ISSUE THREAD

**Issue by jinzhubaofu** [ecomfe/edp#293]
以下代码在build过程中会引起build出错。

``` less
.a {
  background: url('../a.png#xxx');
}
```

原因是在查找对应资源时只处理了`?`，而忽略了`hash`部分。因此导致带着`hash`找本地文件就找不到了。
