### ISSUE TITLE
升级 edp 的 lessc 版本

### ISSUE THREAD

**Issue by Exodia** [ecomfe/edp#305]
遇到这样的情况：

在一个 less 文件中，导入了不同目录的 mixin.less，对路径的生成会造成不一致。如：

``` less
.background (@image-url, @repeat-type:no-repeat, @s-x:0, @s-y:0, @b-color:transparent) {
    @url: ~"@{image-url}";
    @is-url-exp: ~`/^url\([^()]+\)$/i.test("@{url}") ? 'true' : 'false'`;

    .background-image(@is-url-exp) when not (@is-url-exp) {
        background-image: url(@url);
    }
}
```

会生成:

``` css
background-image: url(../img/xxx);
background-image: url(img/xxx);
```
